### ISSUE TITLE
Markdown filter on non-Source object throwing "missing arguments" error

### ISSUE THREAD

**Issue by franktisellano** [lektor/lektor#1100]
I've written a plugin (with a huge amount of help from @dairiki — thanks) that gets public bookmark data from my Pinboard account and exposes it as a Jinja template global. The template looks like this:

```html
{% for link in links %}
  <ul>   
    <li>
      <span class="link-title">
        <a class="link-link" href="{{ link.href }}" target="_blank" rel="noopener">{{ link.description }}</a>
        <small class="link-source">{{ link.source }}</small>
        <span class="link-comments">
          {{ link.comments|markdown }}
        </span>
      </span>
    </li>
  </ul>
{% endfor %}
```

I've upgraded to the [v3.4.0b4](https://github.com/lektor/lektor/releases/tag/v3.4.0b4) release in order to get the benefit of the live reload work done by @frostming and @dairiki, and since that upgrade, my build has started failing with this error:

```
Traceback (most recent call last):
  File "/Users/franktisellano/opt/miniconda3/lib/python3.9/site-packages/lektor/builder.py", line 913, in update
    yield ctx
  File "/Users/franktisellano/opt/miniconda3/lib/python3.9/site-packages/lektor/builder.py", line 1164, in build_artifact
    build_func(artifact)
  File "/Users/franktisellano/opt/miniconda3/lib/python3.9/site-packages/lektor/build_programs.py", line 191, in build_artifact
    artifact.render_template_into(self.source["_template"], this=self.source)
  File "/Users/franktisellano/opt/miniconda3/lib/python3.9/site-packages/lektor/builder.py", line 737, in render_template_into
    rv = self.build_state.env.render_template(
  File "/Users/franktisellano/opt/miniconda3/lib/python3.9/site-packages/lektor/environment/__init__.py", line 229, in render_template
    return self.jinja_env.get_or_select_template(name).render(ctx)
  File "/Users/franktisellano/opt/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/franktisellano/opt/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/franktisellano/Desktop/dev/ftio/templates/links-by-month.html", line 2, in top-level template code
    {% from "macros/link.html" import render_links_by_month %}
  File "/Users/franktisellano/Desktop/dev/ftio/templates/links-layout.html", line 17, in top-level template code
    {% block body %}{% endblock %}
  File "/Users/franktisellano/Desktop/dev/ftio/templates/links-by-month.html", line 6, in block 'body'
    {{ render_links_by_month(links) }}
  File "/Users/franktisellano/opt/miniconda3/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/Users/franktisellano/Desktop/dev/ftio/templates/macros/link.html", line 11, in template
    {{ link.comments|markdown }}
  File "/Users/franktisellano/opt/miniconda3/lib/python3.9/site-packages/lektor/environment/__init__.py", line 138, in <lambda>
    markdown=jinja2.pass_context(lambda ctx, *a, **kw: Markdown(*a, **kw)),
TypeError: __init__() missing 2 required positional arguments: 'record' and 'field_options'
```

Is this a supported use cased for the `markdown` filter? Thanks!

**Comment by franktisellano** [comment]
For completeness' sake, here's the plugin code that gets the bookmarks from Pinboard and returns them as an array of dictionaries. `public_links` is what gets assigned to the template global.

```python
links = pinboard_conn.posts.all()
  for post in links:
    if (post.shared == True):
      post_kv = {
        'description': post.description,
        'comments': post.extended,
        'href': post.url,
        'pub_date': post.time,
        'source': urlparse(post.url).netloc,
        'tags': post.tags
      }
      
      public_links.append(post_kv)
  return public_links
```

**Comment by dairiki** [comment]
I think this is likely a bug introduced in #992.
I'm away from the computer today.  I try to look at this tomorrow.

Thank you for the report!

**Comment by franktisellano** [comment]
Thanks for the fast response! Will go back to a stable release for today. :)

F
