### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'EMBED_SCRIPT' with lektor 3.0.1

### ISSUE THREAD

**Issue by NiklasEi** [lektor/lektor#383]
For the last two days I have been getting the error "AttributeError: 'NoneType' object has no attribute 'EMBED_SCRIPT'". 
On my local server I have lektor 2.3 running and the error does not appear. But when I try to deploy my site (the deployment environment has lektor 3.0.1 running) the error shows. I kept removing code from the file that has the problem and I narrowed it down to the following:

```html
<table>
  <thead>
    <tr>
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><a href="https://www.google.com/">Google</a></td>
    </tr>
  </tbody>
</table>
```

This is in markdown in one of my 'contents.lr'. The problem seems to be with the combination of the table and the link. As soon as I replace the link with some normal text or move it out of the table everything works fine. On my local server with lektor 2.3 I can keep the link in the table and there is no problem at all.

**Comment by nixjdm** [comment]
I'm having trouble reproducing this exactly. Can you post the full traceback, and perhaps which version of mistune you have installed (`pip list` if you've installed via virtualenv)? On 3.0.1 I render your markdown as
`<td><a href="<a href="https://www.google.com/"&gt;Google">https://www.google.com/"&gt;Google</a></a></td>` which is the same output as from 

```
mistune.markdown('''<table>
  <thead>
    <tr>
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><a href="https://www.google.com/">Google</a></td>
    </tr>
  </tbody>
</table>''', escape=False, parse_block_html=True, parse_inline_html=True)
```


My ouput is also wrong, but it is fixed in a following commit that isn't in 3.0.1, commit 2ce0b54. It will be included in the next release after I grok some more of the other changes in master newer than 3.0.1.

**Comment by NiklasEi** [comment]
Mistune is on version 0.7.4

I get the following in the terminal:

```
.
.
.
12:58:57 PM: U projects/CalendarEvents/index.html
12:58:57 PM: U projects/ConnectFour/index.html
12:58:57 PM: U projects/CraftingPlus/index.html
12:58:57 PM: U projects/GameBox/index.html
12:58:58 PM: E projects/GameBox/index.html (AttributeError: 'NoneType' object has no attribute 'EMBED_SCRIPT')
12:58:58 PM: U projects/GemCrush/index.html
12:58:58 PM: U projects/Minesweeper/index.html
12:58:58 PM: U projects/Python-Minesweeper/index.html
.
.
.
1:00:25 PM: An error occurred while building the site, skipping the deploy and cache refresh.
.
.
.
1:00:26 PM: Build script returned non-zero exit code: 1
.
.
.
1:00:27 PM: Error: Build failed with 1 failure.
1:00:27 PM: Finished build in 112.17 sec
1:00:27 PM: Started prune
1:00:27 PM: Finished prune in 0.01 sec
```

**Comment by nixjdm** [comment]
@NiklasEi Could you post your node/npm versions? I'm wondering if you have an older version that didn't install a dependency correctly that's causing this. On the current node (8.1.2) and the npm it grabs, I'm not seeing this. There have been a ton of node updates since 2.3 was released, and I'm thinking that's causing problems for people using older node versions.

**Comment by NiklasEi** [comment]
I was using node v6.11.0 and npm v3.10.10

After seeing this I updated node to v8.1.2 which grabs npm v5.0.3. Now the AttributeError is gone. Thank you!

Now I get the same output you do. The links are still broken, but the site deploys. I will continue manual deploy with lektor 2.4 until the rendering of the links is fixed in the next release.
